title: Kunal's Blog
author: Kunal Geed
email: kunalgeed19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My attempt at recording my journey from a beginner at data science and AI to a Pro. You can find the various projects that I have completed and about my learning experience.

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  KunalGeed # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
